export { default as Dropdown } from './Dropdown';
export { default as Footer } from './Footer';
export { default as Gallery } from './Gallery';
export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Info } from './Info';
export { default as Rating } from './Rating';
export { default as Tag } from './Tag';
export { default as Thumb } from './Thumb';